from enum import StrEnum

from pydantic import BaseModel


class ErrorModel(BaseModel):
    detail: str | dict[str, str]


class ErrorCodeReasonModel(BaseModel):
    code: str
    reason: str


class ErrorCode(StrEnum):
    REGISTER_INVALID_PASSWORD = "REGISTER_INVALID_PASSWORD"  # nosec B105
    REGISTER_USER_ALREADY_EXISTS = "REGISTER_USER_ALREADY_EXISTS"
    OAUTH_NOT_AVAILABLE_EMAIL = "OAUTH_NOT_AVAILABLE_EMAIL"
    OAUTH_USER_ALREADY_EXISTS = "OAUTH_USER_ALREADY_EXISTS"
    OAUTH_INVALID_STATE = "OAUTH_INVALID_STATE"
    LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"
    LOGIN_USER_NOT_VERIFIED = "LOGIN_USER_NOT_VERIFIED"
    RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"  # nosec B105
    RESET_PASSWORD_INVALID_PASSWORD = "RESET_PASSWORD_INVALID_PASSWORD"  # nosec B105
    VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"  # nosec B105
    VERIFY_USER_ALREADY_VERIFIED = "VERIFY_USER_ALREADY_VERIFIED"
    UPDATE_USER_EMAIL_ALREADY_EXISTS = "UPDATE_USER_EMAIL_ALREADY_EXISTS"
    UPDATE_USER_INVALID_PASSWORD = "UPDATE_USER_INVALID_PASSWORD"  # nosec B105
    ACCESS_TOKEN_ALREADY_EXPIRED = "ACCESS_TOKEN_ALREADY_EXPIRED"  # nosec B105
    ACCESS_TOKEN_DECODE_ERROR = "ACCESS_TOKEN_DECODE_ERROR"  # nosec B105
    RENEW_WRONG_ACCESS_TOKEN = "RENEW_WRONG_ACCESS_TOKEN"  # nosec B105
    RENEW_WRONG_REFRESH_TOKEN = "RENEW_WRONG_REFRESH_TOKEN"  # nosec B105
